### PR TITLE
Set up create point of interest page

### LINKED ISSUE #41: Set up Point of Interest Page

### PR DESCRIPTION
**Pull request by mays4**
This PR Resolve issue #60 
created POI form connected the backend to the frontend and added Mapbox to get geocoding for the address and send it back to the backend to save it in the db.

### CODE REVIEW

**Comment by parradaniela** [comment]
Hi Mays, this looks great to me, though my understanding of the back end changes is limited so maybe @camziny can provide some feedback with that part! 

Couple of comments: 
- I noticed that the point of interest form still has the button for light/dark mode. Personally I think we should remove that option from all the forms and keep it in the Profile page. Not a big deal though. 
- I would also change the "Sight.See.Share" heading to something like "Create a Post", as the app's name is already visible on the nav menu 
- I noticed some slightly weird behaviour on the dropdown where there is a line going through the "Choose an option" label. Not sure if this is just a quirk of MUI though? 
image

Other than that, no major changes required in my opinion!

**Comment by mays4** [comment]
> 
> * I noticed that the point of interest form still has the button for light/dark mode. Personally I think we should remove that option from all the forms and keep it in the Profile page. Not a big deal though.
> * I would also change the "Sight.See.Share" heading to something like "Create a Post", as the app's name is already visible on the nav menu
> * I noticed some slightly weird behaviour on the dropdown where there is a line going through the "Choose an option" label. Not sure if this is just a quirk of MUI though?
>   image
> 
> Other than that, no major changes required in my opinion!

Thank you @parradaniela  I fixed all the issues you mentioned, Can you please check if they are okay now

**Comment by parradaniela** [comment]
Looks great Mays!

**Review by camziny — APPROVED** [review]
Great job @mays4! This definitely looks like it was a bit of a challenge. The only thing I noticed was a couple of commented out lines in the PostForm.tsx file. If they aren't needed any longer we can probably get rid of them, otherwise well done!

**Comment by mays4** [comment]
> Great job @mays4! This definitely looks like it was a bit of a challenge. The only thing I noticed was a couple of commented out lines in the PostForm.tsx file. If they aren't needed any longer we can probably get rid of them, otherwise well done!

Thank you @camziny   I removed them

**Pull request merged**
