### PR TITLE
Initialize backend models

### PR DESCRIPTION
**Pull request by camziny**

### CODE REVIEW

**Comment by chris-t-li** [comment]
Hey @camziny, for some reason the node_modules folder was not ignored by git. Are you able to update .gitignore so that they are not tracked?

**Comment by camziny** [comment]
> Hey @camziny, for some reason the node_modules folder was not ignored by git. Are you able to update .gitignore so that they are not tracked?

Ok, I just updated it. I think that should work.

**Comment by chris-t-li** [comment]
Thanks, also, should we remove the node_modules folder in the root directory? 

Screen Shot 2023-08-23 at 11 21 49 AM

**Comment by camziny** [comment]
> Thanks, also, should we remove the node_modules folder in the root directory?
> 
> Screen Shot 2023-08-23 at 11 21 49 AM

That' fine with me. Want me to delete it in this branch?

**Comment by chris-t-li** [comment]
> > Thanks, also, should we remove the node_modules folder in the root directory?
> > Screen Shot 2023-08-23 at 11 21 49 AM
> 
> That' fine with me. Want me to delete it in this branch?

Sure!

**Review by chris-t-li — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
