### PR TITLE
new auth/routes, error class added, security edits in the backend

### PR DESCRIPTION
**Pull request by mtoprak53**
For Issues #37 & #38:

Added expressError.ts for specific error subclasses.

Edited src/middleware/auth.ts to include ensureLoggedIn and ensureCorrectUser, and changed verifyToken to only get the token if it exists without any error for non-existence.

Edited src/config/db.ts to specify connection parameters.

Edited src/controllers/post.controller.ts to add getPostsByPoi and getPostsByUser.

Edited src/controllers/user.controller.ts to prevent loginUser from returning the user's passwords.

Edited src/routes/post.route.ts to add getPostsByPoi and getPostsByUser endpoints, and add ensureCorrectUser middleware for POST/UPDATE/DELETE post endpoints.

Edited src/routes/user.route.ts to add ensureCorrectUser middleware for UPDATE/GET user endpoints.

### CODE REVIEW

**Review by camziny — COMMENTED** [review]
Hey @mtoprak53, some cool changes here. One thing I noticed while I was testing is that we might encounter ambiguity in our routes because the same URL structure is used for both getPostsByPoi and getPostsByUser endpoints, and it seems like Express will match the first route that matches the URL pattern.

For example, I commented out the following line:
- postRouter.get("/:userId", getPostsByUser);

and made a GET request at the url: http://localhost:3000/posts/1

As expected, all posts with poiId of 1 were returned. 

I then commented out the the line: 
- postRouter.get("/:poiId", getPostsByPoi);

and made a GET request at the url: http://localhost:3000/posts/1

As expected, all posts with a userId of 1 were returned. 

However, when I left both endpoints uncommented, all posts with poiId of 1 were returned.

**Comment by camziny** [comment]
Maybe as long as our frontend code correctly constructs the requests with the appropriate parameter name based on whether it's fetching posts by POI ID or User ID then it won't be an issue.

**Comment by mtoprak53** [comment]
You are right @camziny. I missed that. I'm making the necessary changes.

**Review by camziny — COMMENTED** [review]
One more thing I noticed is that we added back all of the User properties into the loginUser function, instead of having just email and password. Is that intentional?

**Comment by mtoprak53** [comment]
Actually, in the old version, all user information, including the password, was returned as a JSON parameter in the existingUser. I intentionally removed the password because it is not needed after user verification and it is the most sensitive user information. I left the rest of the information in the JSON return for any possible frontend needs, but it might be reduced if it is determined that certain information is definitely not needed after login.

**Review by mays4 — COMMENTED** [review]
Good work, I like that you have a file for error express, I just want to check as Cam mentioned in his comment why we get all fields in the logged user not just email and password

**Review by mays4 — COMMENTED** [review]
Also, I don't see that you are using ensureLoggedIn and verify token

**Comment by mtoprak53** [comment]
> Good work, I like that you have a file for error express, I just want to check as Cam mentioned in his comment why we get all fields in the logged user not just email and password

I already replied this, but let me try to explain differently: I did not add anything extra in what info to return, the former version was returning all these info + password. I just removed the password from what info to return.

**Comment by mtoprak53** [comment]
> Also, I don't see that you are using ensureLoggedIn and verify token

Yes you are right. I have to edit `pointOfInterest.route.ts`, `ensureLoggedIn` will be used over there. 
And `verifyToken` is only used in `index.ts` line:25 to get any present token at the beginning.

Update: I added `ensureLoggedIn` in `pointOfInterest.route.ts`

**Review by camziny — APPROVED** [review]
Everything seems to work for me. We might just want to remove some of the console logs that were added for testing.

**Review by camziny — COMMENTED** [review]
I actually just noticed we also removed the `IUser` interface from loginUser within user.controller.ts.

**Comment by mtoprak53** [comment]
Thanks for the last two edit suggestions @camziny. I put `IUser` back in `loginUser`, and removed the `console.log()`s in last two commits.

**Comment by mays4** [comment]
I think @mtoprak53 you are using an old version that's why you are seeing in the login user all the info in the updated version in the main We don't have it we removed it a long time ago. So can you please remove them

**Comment by mays4** [comment]
Thank you for the explanation of the use of the auths

**Comment by mtoprak53** [comment]
> I think @mtoprak53 you are using an old version that's why you are seeing in the login user all the info in the updated version in the main We don't have it we removed it a long time ago. So can you please remove them

OK. That's what you get when you log in to the current main branch, if I am not doing something very wrong: 
```
{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjk0MjgxODg2LCJleHAiOjE2OTQ4ODY2ODZ9.Q3IC8MyozAUJ5PKq6W-43rPDtYid17l1KxIRD1S3BXc",
	"existingUser": {
		"id": 6,
		"first_name": "yoyo",
		"last_name": "nono",
		"user_name": "yoyo61",
		"occupation": "forklift operator",
		"password": "$2b$12$5uK.bIWFhgayeuklAcbeGue6k2Pjzxmozv.sZAjo9fguUmccTyAwe",
		"email": "yoyo@nono.xyz",
		"location": "frankfurt",
		"profile_image": "https://rb.gy/i5nt0",
		"createdAt": "2023-09-08T01:07:44.983Z",
		"updatedAt": "2023-09-08T01:07:44.983Z"
	}
}
```
Nothing has been removed by YOU.

I am not behind on any commits. Up to this point, I have tried to explain what I have done and what it does. However, this last objection of yours does not even have a rational basis. You can at least check it in the Postman, what you get in return when you log in.

And please, never again talk to me in an ordering manner about what I have to do.

I showed my goodwill until the end of your abuse. This is the line.

If you need more edits on what the login returns, you can easily code it and make a PR after my merge.

I appreciate all the work done in the project. And it was not easy for me to pick up too many new stuff at once, and I am trying to contribute in the project anyways. But goodwill and respect is vital.

**Pull request merged**
